image: buildstream/buildstream:latest-master-52125390

cache:
  paths:
    - cache/

stages:
  - prepare
  - test
  - docs
  - upload

before_script:
  - adduser -m buildstream
  - chown -R buildstream:buildstream .

  - dnf install -y quilt

#####################################################
#                  Prepare stage                    #
#####################################################

# Create a source distribution
#
source_dist:
  stage: prepare
  script:

  # Generate the source distribution tarball
  #
  - python3 setup.py sdist
  - tar -ztf dist/*
  - tarball=$(cd dist && echo $(ls *))

  # Create an installer script
  - |
    cat > dist/install.sh << EOF
    #!/bin/sh
    tar -zxf ${tarball}
    cd ${tarball%.tar.gz}
    pip3 install --no-index .
    EOF

  # unpack tarball as `dist/bst-external` directory
  - |
    cat > dist/unpack.sh << EOF
    #!/bin/sh
    tar -zxf ${tarball}
    mv ${tarball%.tar.gz} bst-external
    EOF

  # Make our helpers executable
  - chmod +x dist/install.sh
  - chmod +x dist/unpack.sh
  artifacts:
    paths:
    - dist/

#####################################################
#                    Test stage                     #
#####################################################
.tox-template: &tox
  stage: test
  before_script:
    - pip3 install --upgrade pip tox tox-venv
    - useradd -Um buildstream
    - chown -R buildstream:buildstream .
  script:
    - su buildstream -c tox
  variables: &tox-variables
    PY_COLORS: 1
    PYTEST_ADDOPTS: '--color=yes'

tests-py37:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: py37

tests-py36:
  <<: *tox
  image: python:3.6-stretch
  variables:
    <<: *tox-variables
    TOXENV: py36

tests-py35:
  <<: *tox
  image: python:3.5-stretch
  script:
    # Plugins behave weirdly inside tox on Python 3.5 only. To further the
    # weirdness, the tests work fine when preparing the environment separately
    # from running tests.
    - su buildstream -c sh -c 'tox --notest'
    - su buildstream -c tox
  variables:
    <<: *tox-variables
    TOXENV: py35

lint:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: lint rst-lint

docs-test:
  <<: *tox
  variables:
    <<: *tox-variables
    TOXENV: docs
  script:
    - su buildstream -c tox
    - mv doc/build/html public
  artifacts:
    paths:
    - public/


# Automatically build documentation, only for merges which land
# on master branch.
#
# Note: We still do not enforce a consistent installation of python2
#       or sphinx, as python2 will significantly grow the backing image.
#

#####################################################
#                  Docs stage                       #
#####################################################

pages:
  stage: docs
  script:
    - find public/
  artifacts:
    paths:
    - public/
  only:
  - master
  dependencies:
    - docs-test


# Automatically upload to PyPI when a release is tagged.

#####################################################
#               Upload stage                        #
#####################################################

upload:
  stage: upload
  before_script:
    - pip3 install requests
    - pip3 install twine

  script:
  - twine upload dist/*.tar.gz
  dependencies:
  - source_dist
  only:
  - /[0-9]+\.[0-9]+\.[0-9]+/
  except:
  - branches
